// src/main/java/com/example/docsign/crypto/AdminPurgeService.java
package com.example.docsign.services;

import com.example.docsign.model.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class AdminPurgeService {

  private final KeyPairRecordRepository keyRepo;
  private final CertificateRecordRepository certRepo;
  private final CsrRecordRepository csrRepo;
  private final Path baseDir;

  public AdminPurgeService(KeyPairRecordRepository keyRepo,
                           CertificateRecordRepository certRepo,
                           CsrRecordRepository csrRepo,
                           @Value("${app.storage.base-path}") String basePath) throws IOException {
    this.keyRepo = keyRepo;
    this.certRepo = certRepo;
    this.csrRepo = csrRepo;
    this.baseDir = Paths.get(basePath).toAbsolutePath().normalize();
    Files.createDirectories(this.baseDir);
  }

  public record PurgeReport(
      int deletedCsrs,
      int deletedCerts,
      int deletedKeys,
      List<String> deletedPaths
  ) {}

  /** Purge everything generated by users. Keeps system keys by default. */
  @Transactional
  public PurgeReport purgeAll(boolean includeSystem) throws IOException {
    var deletedPaths = new ArrayList<String>();

    // 1) Pick target key set
    List<KeyPairRecord> keys = includeSystem
        ? keyRepo.findAll()
        : keyRepo.findBySystemKeyFalse();

    var keyIds = keys.stream().map(KeyPairRecord::getId).collect(Collectors.toSet());

    // 2) Delete CSRs that belong to those keys
    List<CsrRecord> csrs = keyIds.isEmpty()
        ? List.of()
        : csrRepo.findAll().stream()
            .filter(c -> c.getKeyPair() != null && keyIds.contains(c.getKeyPair().getId()))
            .toList();

    for (var c : csrs) {
      deleteFileIfExistsSafe(c.getCsrPath(), deletedPaths);
    }
    csrRepo.deleteAll(csrs);
    int deletedCsrs = csrs.size();

    // 3) Delete certs that belong to those keys
    List<CertificateRecord> certs = keyIds.isEmpty()
        ? List.of()
        : certRepo.findAll().stream()
            .filter(c -> c.getKeyPair() != null && keyIds.contains(c.getKeyPair().getId()))
            .toList();

    for (var cert : certs) {
      deleteFileIfExistsSafe(cert.getCertificatePath(), deletedPaths);
    }
    certRepo.deleteAll(certs);
    int deletedCerts = certs.size();

    // 4) Delete key folders (e.g., ./data/keys/{id})
    int deletedKeys = 0;
    for (var k : keys) {
      // delete recorded files if any (public/private)
      deleteFileIfExistsSafe(k.getPublicKeyPath(), deletedPaths);
      deleteFileIfExistsSafe(k.getPrivateKeyPath(), deletedPaths);

      // also nuke the entire key directory if it exists
      Path keyDir = baseDir.resolve(Paths.get("keys", String.valueOf(k.getId()))).normalize();
      if (isUnderBase(keyDir) && Files.exists(keyDir)) {
        deleteTree(keyDir, deletedPaths);
      }
      deletedKeys++;
    }
    keyRepo.deleteAll(keys);

    //also clean empty top-level folders
    cleanupEmptyDirs("csr", deletedPaths);
    cleanupEmptyDirs("certs", deletedPaths);
    cleanupEmptyDirs("keys", deletedPaths);

    return new PurgeReport(deletedCsrs, deletedCerts, deletedKeys, deletedPaths);
  }

  /* ---------- filesystem helpers ---------- */

  private boolean isUnderBase(Path p) {
    return p != null && p.normalize().startsWith(baseDir);
  }

  private void deleteFileIfExistsSafe(String storedPath, List<String> out) throws IOException {
    if (storedPath == null || storedPath.isBlank()) return;
    Path p = Paths.get(storedPath);
    Path abs = p.isAbsolute() ? p.normalize() : baseDir.resolve(p).normalize();
    if (!isUnderBase(abs)) return; // ignore anything outside base dir
    try {
      if (Files.deleteIfExists(abs)) out.add(abs.toString());
    } catch (IOException e) {
      // If delete fails, rethrow to abort tx (keeps DB consistent)
      throw e;
    }
  }

  private void deleteTree(Path dir, List<String> out) throws IOException {
    if (!isUnderBase(dir) || !Files.exists(dir)) return;
    // Walk bottom-up
    try (var walk = Files.walk(dir)) {
      List<Path> all = walk.sorted(Comparator.reverseOrder()).toList();
      for (Path p : all) {
        try {
          Files.deleteIfExists(p);
          out.add(p.toString());
        } catch (IOException e) {
          throw e;
        }
      }
    }
  }

  private void cleanupEmptyDirs(String top, List<String> out) throws IOException {
    Path d = baseDir.resolve(top).normalize();
    if (!isUnderBase(d) || !Files.exists(d)) return;
    try (var walk = Files.walk(d)) {
      var dirs = walk.filter(Files::isDirectory).sorted(Comparator.reverseOrder()).toList();
      for (Path p : dirs) {
        try {
          if (Files.list(p).findAny().isEmpty()) {
            Files.deleteIfExists(p);
            out.add(p.toString());
          }
        } catch (IOException ignored) {
          // ignore permissions/locks on cleanup
        }
      }
    }
  }
}
