# Application name
spring.application.name=docsign

# Server
server.port=8080

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/docsign
spring.datasource.username=docsign_user
spring.datasource.password=secretpassword

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# App custom config
app.storage.base-path=./data


# CA key/cert locations
app.ca.intermediate.key-path=private/ca/intermediate/private.pem
app.ca.intermediate.cert-path=private/ca/intermediate/cert.pem

app.ca.root.key-path=private/ca/root/private.pem
app.ca.root.cert-path=private/ca/root/cert.pem

# used only for CA creation
app.ca.root.key-id=1
app.ca.intermediate.key-id=2


# application.properties
docseal.sign.max-pdf-mb=10
docseal.sign.max-doc-mb=50
docseal.sign.default-hash=SHA-256
docseal.sign.default-sig=RSA-PSS 